import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle";
import { WarpBackground } from "@/components/magicui/warp-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <header className="fixed mb-10 top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-sm p-4 flex justify-between items-center border-b">
            <div className="text-6xl font-bold">Central Electricity Authority  (Reception)</div>
            <div>
              <ModeToggle />
            </div>
          </header>
          <WarpBackground>
          <main className="pt-20 min-h-screen">
            {children}
          </main>
          </WarpBackground>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}